version: '3'

services:
  java-app:
    image: web-app:latest
#    depends_on:
#      postgres-db:
#        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
    ports:
      - "8080:8081"
    restart: always

  postgres-db:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
#    healthcheck:
#      test: [ "CMD-SHELL", "pg-isready -U postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
    volumes:
      - /home/web/postgres-data:/var/lib/postgresql/data
