<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Document</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col">

        </div>
        <div class="col">
            <p>Hello, ${name} ${secondName}</p>
        </div>
        <div class="col">

        </div>
    </div>

    <div class="row">
        <div class="col">

        </div>
        <div class="col">
            <a href="/web/logout" class="btn btn-primary">Logout</a>
        </div>
        <div class="col">

        </div>
    </div>
    <div class="row">
        <div class="col">

        </div>
        <div class="col">
            <a href="/web/hats">hats</a>
        </div>
        <div class="col">

        </div>
    </div>
</div>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>